name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Save Docker Images
        run: docker build . -t paas-dashboard:go; docker save paas-dashboard:go -o paas-dashboard-go.tar.gz
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: paas-dashboard-go.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
